name: Build-Push Docker image

on:
  push:
    branches:
      - "develop-aks-keycloak"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SOLOCODE_USERNAME }}
          password: ${{ secrets.SOLOCODE_TOKEN }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.SOLOCODE_USERNAME }}/evofast-backend-aks-keycloak:${{ env.IMAGE_TAG }}

      - name: Checkout Helm chart repo
        uses: actions/checkout@v3
        with:
          repository: EvofastEnglish/evofast-backend-chart
          token: ${{ secrets.GH_TOKEN }}
          ref: develop-k3s-keycloak
          path: evofast-backend-chart

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update values.yaml with new image tag
        run: |
          cd evofast-backend-chart
          yq eval '.image.tag = strenv(IMAGE_TAG)' -i values.yaml

          git config user.email "ci-bot@github.com"
          git config user.name "CI Bot"

          git commit -am "chore: update image tag to ${{ env.IMAGE_TAG }}"
          git push origin develop-k3s-keycloak
