name: Build-Push Docker Image

on:
  push:
    branches:
      - "develop"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SOLOCODE_USERNAME }}
          password: ${{ secrets.SOLOCODE_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.SOLOCODE_USERNAME }}/caresmily-backend:latest
      -
        name: Create trigger 
        run: |
          curl -k "https://lieudvq0302:114cc4eb6e926ebcb4a481b76c3ca1f9d1@jenkins.solocode.click/job/caresmily-backend/build?token=buildtoken"
